#!/bin/bash
#COBALT -t 60
#COBALT -n ${NNODES}
#COBALT --attrs mcdram=cache:numa=quad
#COBALT -A CSC250STDM11
#COBALT --queue default

export PATH=$PATH:${PERF_ROOT}/adiosvm/Tutorial/gray-scott/build
