#!/bin/bash -l
#SBATCH -N ${NNODES}
#SBATCH -t 00:30:00
#SBATCH -L SCRATCH
#SBATCH -C haswell
#SBATCH -J gray-scott
#SBATCH --gres=craynetwork:2
#SBATCH -A m499

export PATH=$PATH:${PERF_ROOT}/adiosvm/Tutorial/gray-scott/build
export PATH=$PATH:${DSPACES_INSTALL}/bin
